name: pit
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  google_fonts: ^4.0.4
  pin_code_fields: ^7.3.0
  flutter_markdown: ^0.6.7
  sqflite: any
  provider: ^6.0.1
  image_picker: 0.7.0-nullsafety
  path_provider: ^2.0.11
  path_provider_android: ^2.0.14

  qr_code_scanner: ^1.0.1

  #firebase package for cloud messaging

  #show local notifications
  flutter_local_notifications: ^9.5.3+1
  firebase_core_platform_interface: 4.5.2
  #listen for notification
  rxdart: ^0.27.4

  http: ^0.13.4
  #  device_info: ^2.0.2
  intl: any
  #check internet connections

  #  internet_connection_checker: ^0.0.1+3
  syncfusion_flutter_gauges: ^19.3.48

  geolocator: ^7.0.2
  geocoding: ^2.0.1
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  #hive database generator
  build_runner: ^2.0.6
  hive_generator: ^1.0.1
  # display signature
  signature:
    ^5.0.0
    # save signature
  #  permission_handler: ^5.1.0+2
  permission_handler: ^9.2.0
  #  image: ^3.1.3

  device_apps: ^2.2.0
  flutter_lints: ^1.0.4
  flutter_datetime_picker_plus: ^2.2.0
  # flutter_datetime_picker:
  #   git:
  #     url: https://github.com/Realank/flutter_datetime_picker.git
  #     ref: master
  #  firebase_core: ^1.18.0
  #  firebase_core: ^1.21.1
  firebase_core: ^2.4.0

  #  firebase_messaging: ^12.0.3
  firebase_messaging: ^14.1.1
  #  overlay_support: ^2.0.1
  flutter_app_badger: ^1.4.0
  #test jaringan internet klo ok hapus comment ini
  #  cross_connectivity: ^3.0.5
  connectivity_plus: ^2.3.5
  device_info_plus: ^4.0.0
  #location: ^4.0.0
  #geocoding: ^2.0.1
#  flutter_launcher_icons: "^0.9.2"
#flutter_icons:
#  android: "launcher_icon"
#  ios: false
#  image_path: "assets/icon/logo_pit.png"
#  adaptive_icon_background: "assets/icon/background_white.png"
#  adaptive_icon_foreground: "assets/icon/background_white.png"
dependency_overrides:
    win32: ^5.5.4
dev_dependencies:
  flutter_test:
    sdk: flutter

#  shared_preferences: ^2.0.5
#  google_fonts: ^2.0.0
#  pin_code_fields: ^7.3.0
#  flutter_markdown: ^0.6.7
#  sqflite: any
#  provider: ^6.0.1
#  image_picker: 0.7.0-nullsafety
#  path_provider: any
#  http: ^0.13.4
#  device_info: ^2.0.2
#  intl: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
